### ISSUE TITLE
issue with ruby 2.3.0

### ISSUE THREAD

**Issue by thomasgalibert** [stefanpenner/country_select#114] opened 2015-10-16 11:08 UTC
I'v have an issue with a Rails project, version 4.2.4 and ruby 2.3.0 

error message appears : "can't modify frozen String" when starting webserver

I did not have this issue with ruby 2.1 but have to work with > 2.2.2 to test some Rails 5 prototypes.

Thanks.

**Comment by scudco** [comment] 2015-10-18 21:02
Looking at the stacktrace in travis for `ruby-head`, it looks like it is indeed throwing this error, but it's occurring in `unicode-utils` and is triggered by the require of `sort_alphabetical`. 

```
/home/travis/build/stefanpenner/country_select/gemfiles/vendor/bundle/ruby/2.3.0/gems/unicode_utils-1.4.0/lib/unicode_utils/read_cdata.rb:183:in `read': can't modify frozen String (RuntimeError)
```

Here's the link to the build with the stacktrace https://travis-ci.org/stefanpenner/country_select/jobs/81409385

Is that the same kind of stacktrace you're receiving?

**Comment by thomasgalibert** [comment] 2015-10-19 15:52
Yes, exactly the same error !

**Comment by twalpole** [comment] 2015-11-20 01:21
Debugging this with ruby 2.3.0-preview1 if you have a string which you force encoding to and then use as the buffer of a file read, and then call to_sym on it, the string gets frozen - I can't believe this is intended behavior

file = File.open('some_file.txt')
a = ""
a.force_encoding(Encoding::US_ASCII)  # if this isn't done the string doesn't get frozen
file.read(2, a) #after this line a is still unfrozen
a.to_sym #after this a becomes frozen

**Comment by twalpole** [comment] 2015-11-20 19:45
Fixed in https://bugs.ruby-lang.org/projects/ruby-trunk/repository/revisions/52686

**Closed** 2016-01-02 18:51 UTC
