### ISSUE TITLE
High memory consumption

### ISSUE THREAD

**Issue by zywx** [stefanpenner/country_select#107] opened 2015-08-07 12:20 UTC
Using http://engineering.heroku.com/blogs/2015-08-06-patching-rails-performance/

country_select consumes 26M, mostly because of iso3166.

**Comment by stefanpenner** [comment] 2015-08-07 14:02
Although this affects country_select, I believe the source of the issue is https://github.com/hexorx/countries/

**Comment by dgilperez** [comment] 2015-08-25 14:40
Countries gem just released a new version to address this issue: https://github.com/hexorx/countries/pull/285

They hit 1.0, with a few major changes, so we cannot use it directly with current version of `country_select`

**Comment by scudco** [comment] 2015-08-25 17:56
Fixed by #108

**Closed by scudco** 2015-08-25 17:56 UTC

**Comment by zywx** [comment] 2015-08-26 10:52
Well done!
